# Generated by Django 4.0.3 on 2022-04-14 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название кники')),
                ('author', models.CharField(max_length=50, verbose_name='Автор')),
                ('price', models.IntegerField(max_length=5, verbose_name='Цена')),
                ('status', models.CharField(max_length=10, verbose_name='Способ заказа')),
            ],
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
    ]
